# You must restart the bot if you modify this file.

discord:
  bot_owner:            ""
  # Your Discord token. See https://discordpy.readthedocs.io/en/stable/discord.html
  token:                ""
  server:               id_server
  chan:                 id_chan

mysqlclient:
  host:                 ""
  user:                 ""
  password:             ""
  database:             ""
  # For MariaDB in Debian 13
  charset:              "utf8mb4"
  collation:            "utf8mb4_unicode_520_ci"
# Since we’re doing “MySQLdb.connect(**Config["mysqlclient"])”, adding custom parameters in
# Config["mysqlclient"] cause a silent failure
db_additional:
  history_table:        "history"

history_storage:        ""
mail_server:            ""
bot_mail_address:       ""

irc:
  bot_owner:            ""
  server:               "irc.libera.chat"
  chan:                 "#chan"
  nick:                 "MyBot"
  password:             ""
  username:             "my_bot"
  real_name:            "My Bot"
  quit_message:         "That’s the end of the line"

# If you want messages on Discord displayed as coming from the users instead of the bot.
# See https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
webhooks:
  PutHereAnIrcChan: ""

irc_users:
  PutHereAnIrcNick1:
    discord_username:   ""
  PutHereAnIrcNick2:
    discord_username:   ""
    avatar:             "https://domain.tld/path/to/Avatar.jpeg"
