# You must restart the bot if you modify this file.

mail_server:            ""
bot_mail_address:       ""

discord:
  bot_owner:            ""
  # Your Discord token. See https://discordpy.readthedocs.io/en/stable/discord.html
  token:                ""
  server:               id_server
  chan:                 id_chan

irc:
  bot_owner:            ""
  server:               "irc.libera.chat"
  chan:                 "#chan"
  nick:                 "MyBot"
  password:             ""
  username:             "my_bot"
  real_name:            "My Bot"
  quit_message:         "Something clever"
