# You must restart the bot if you modify this file.

mail_server:            ""
bot_mail_address:       ""

discord:
  bot_owner:            ""
  # Your Discord token. See https://discordpy.readthedocs.io/en/stable/discord.html
  token:                ""
  server:               id_server
  chan:                 id_chan

irc:
  bot_owner:            ""
  server:               "irc.libera.chat"
  chan:                 "#chan"
  nick:                 "MyBot"
  password:             ""
  username:             "my_bot"
  real_name:            "My Bot"
  quit_message:         "Something clever"

# If you want messages on Discord displayed as coming from the users instead of the bot.
# See https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
webhooks:
  PutHereAnIrcChan: ""

irc_users:
  PutHereAnIrcNick1:
    discord_username:   ""
  PutHereAnIrcNick2:
    discord_username:   ""
    avatar:             "https://domain.tld/path/to/Avatar.jpeg"
